### ISSUE TITLE
Time of comment in the future / can not delete comment

### ISSUE THREAD

**Issue by MDXDave** [presentator/presentator#105]
![image](https://user-images.githubusercontent.com/6099976/62461514-5cfb0980-b785-11e9-96d9-dcc07bdf4efc.png)

I have added a comment to a screen a few minutes ago, it will be shown "in 2 hours" instead of "now" or "for 2 minutes".

I do not know if its related to this issue, but i can not delete the comment.#

**Edit** It seems that you can not delete the first comment in a conversation

**Comment by ganigeorgiev** [comment]
Here [CommentPopover.vue#44](https://github.com/presentator/presentator/blob/master/packages/spa/src/views/comments/CommentPopover.vue#L344) `this.replies` should be `this.commentsList`. It is already fixed in the develop branch.

The fix for the bug will be included in v2.0.1 release (later today or at the latest by tomorrow).

**Comment by ganigeorgiev** [comment]
Merged in master and included in v2.0.1 release.
Once again, if you are using the [presentator-starter](https://github.com/presentator/presentator-starter), just run `composer update` to get the latest changes.
