### ISSUE TITLE
Missing translation strings

### ISSUE THREAD

**Issue by MDXDave** [presentator/presentator#106]
The following strings can not be translated using Transifex:

## Hotspot
Successfully updated hotspot.
Screen cannot be blank.
Url cannot be blank.

## Security
Invalid password.
New password should contain at least 6 characters.
New password confirm should contain at least 6 characters.
Oops, an error occurred while processing your request.

**Comment by ganigeorgiev** [comment]
Thanks for reporting the issue. I've added the missing the translations ("Successfully updated hotspot." and "Successfully updated user password.") in the develop branch and updated the Transifex SPA source file.
Note that most of the form error messages are already translated in Yii and will be available in your preferred language once the language is added to the supported list.

The fix for the bug will be included in v2.0.1 release (later today or at the latest by tomorrow).

**Comment by ganigeorgiev** [comment]
Merged in master and included in v2.0.1 release.
If you are using the [presentator-starter](https://github.com/presentator/presentator-starter), just run `composer update` to get the latest changes.
