### ISSUE TITLE
I didn't found 'Fit to screen' on the v2.0.5

### ISSUE THREAD

**Issue by Laul0** [presentator/presentator#113]
First, thank you! I use  Presentator since a lot of year and I really appreciate it ❤️

This new version with this new interface is awesome 🙂

I didn't found the function named "Fit to screen" that was really useful into the previous version. This is normal? I'm missing something?

<img width="224" alt="Screen Shot 2019-08-13 at 21 06 43" src="https://user-images.githubusercontent.com/15279205/62987542-4b150880-be0e-11e9-8f90-bb6f68480e68.png">

**Comment by ganigeorgiev** [comment]
Actually this was intentional. I decided to remove it because the preview bar is already too cluttered (especially when you have more than 1 prototype) and personally me and my coworkers didn't actually use the option (we were actively using it for mobile screens before "Auto scale" was introduced).

Before adding it again, could you explain your use case (aka. in which situations you find "Fit to screen" to be useful)?

**Comment by Laul0** [comment]
Hi @ganigeorgiev, yes I can explain.
It is mostly because when some user have a lower resolution screen than the mockup or sometime a picture; they have to scroll right to left as well as top to bottom.
With the Fit to screen, they can just scroll from top to bottom, it is pretty useful.

**Comment by ganigeorgiev** [comment]
Merged in master and included in v2.1.0 release.
