### ISSUE TITLE
Linking hotspots from different projects

### ISSUE THREAD

**Issue by ghs** [presentator/presentator#12]
Normally designers present their work for all devices at once and having the possibility to link one screen to another is great, but will be greater if could make a link to the corresponding version on mobile or tablet.
Currently only the screens within the specific project can be used by the hotspot links.
Of course somebody could add a mobile version of that screen to the desktop project, but then the use of different project types makes no sense.

**Comment by ganigeorgiev** [comment]
I'm not sure how the UI should looks and react. There is also some major things that need to be considered like passwords handling between linked projects and such.

I'll leave the discussion open, because the idea is not bad, but requires very detailed considerations over the possible changes.

**Comment by ghs** [comment]
Indeed! :)

**Comment by danicatalan** [comment]
I'm agree with @ghs, I don't really understand how the device selection adds value to the whole project.

Otherwise I see a lot of value on the viewport limit. Maybe screens can be displayed by default, and admins can manually add sizes to the screens to force overflows and simulate the viewport constrains.

**Comment by ganigeorgiev** [comment]
@danicatalan Project types (aka. Single project per device) was suggested during the beta and the idea behind that was to provide simple mechanism to distinguish multiple project variations in addition to the versions option.

A month ago I also received a suggestion to update the project types and to implement them per version, ex. to be able to set V1 for desktop and V2 for mobile. This way, you could easily refer to a screen with different viewport size.

I like your idea to enable the users to set manually the viewport constrains per screen, but I also worry that this will make the interface a little more confusing.

Currently if you want to link screens from different versions/projects you could copy the project preview link with the approriate "#v{Number}-s{Number}" tag (eg. https://app.presentator.io/bg/123Test#v2-s1) and set it as a Hotspot Custom url value.

**Comment by danicatalan** [comment]
> Currently if you want to link screens from different versions/projects you could copy the project preview link with the approriate `#v{Number}-s{Number}` tag (eg. https://app.presentator.io/bg/123Test#v2-s1) and set it as a Hotspot Custom url value.

Aha! It works like a charm. That's cool :)

**Comment by ganigeorgiev** [comment]
With v2, the preview url format has changed and if you need to link to a different project/prototype screen, you could use `/prototypes/{prototypeId}/screens/{screenId}`.

I'm closing this issue for now, since the previously discussed problems are still valid for v2 (eg. passwords handling between linked protected projects).

If anyone thinks that this should be implemented in future v2.x releases, please comment and I'll reopen the issue.
