### ISSUE TITLE
Better screens selection in a prototype

### ISSUE THREAD

**Issue by flayks** [presentator/presentator#129]
That would be great if we could select all screens on a prototype using a button or a shortcut (Cmd/Ctrl + A?) and also have the ability to select multiples from one to a specific one using the Shift key, like you could do on a file manager (Finder or Explorer)

**Comment by ganigeorgiev** [comment]
@flayks It is not documented but to some extent this is implemented already. The following listing shortcuts should works:

- `Ctrl + A` - select all screens in a single prototype
- `Ctrl + Screen thumb click` - select a single screen (alternative to just clicking the checkbox)
- `ESC` - cancel selection/operation

_only in screen preview:_

- `G` - switch to "Guideline"
- `P` - switch to "Preview mode"
- `H` - switch to "Hotspots mode"
- `C` - switch to "Comments mode"

The `Shift + Click` is not added because i don't want to prevent the default browser behavior to open the screen in a new tab/window.

**Comment by flayks** [comment]
Oh okay, good to know. Indeed the select all shortcut works but with Ctrl on Mac and not Cmd. Ctrl + Left click actually opens the contextual menu on the link. Maybe the behaviors are not the best for Mac (Chrome)?
For Shift + Click I think, because it's a tool, that it wouldn't be too bad to bypass the default browser behavior and keep the right click contextual menu options to open a screen in a new tab or window, etc.
