### ISSUE TITLE
Customizing footer

### ISSUE THREAD

**Issue by ArjonBu** [presentator/presentator#130]
Is it possible to customize the footer to add a privacy policy and a contact link/page? 

Thank you for this great software

**Comment by ganigeorgiev** [comment]
@ArjonBu Currently there is no such option.

You can change the "Terms and Privacy policy" url (visible on the [sign up page](https://app.presentator.io/#/sign-up)) with [VUE_APP_TERMS_URL](https://github.com/presentator/presentator/blob/master/packages/spa/.env#L10) parameter.

What is your use case?  It could be added as another config parameter(s), but I'm not sure whether that will not clutter unnecessary the UI.

**Comment by ArjonBu** [comment]
Where do I create this file? In the root directory or root/web? 

The usecase is to add some information and some form of contact details for the company

**Comment by ganigeorgiev** [comment]
If you are using [presentator-starter](https://github.com/presentator/presentator-starter), the SPA config parameters could be set in the `spaConfig` [section of your composer.json](https://github.com/presentator/presentator-starter/blob/master/composer.json#L48). After that, you'll have to run `composer install` (or `composer run-script post-install-cmd`) in order to trigger the post installation script.

If you've installed the SPA and API packages separately, then you can change the SPA configurations in the [.env.*](https://github.com/presentator/presentator-spa/blob/master/.env) file of your project and after that run `npm run build` to generate the new `dist` files.

The footer view is located at [presentator-spa/src/views/base/AppFooter.vue](https://github.com/presentator/presentator-spa/blob/master/src/views/base/AppFooter.vue).

---

In my opinion, because almost every self hosted setup of the application is mainly intended for internal company usage, I don't think that it will be practical to constantly show the privacy policy or contact details for the same company in the app footer.

I'm closing the issue for now, but if anyone else disagree, please comment and I'll consider adding additional configurations for the next release.

**Comment by ArjonBu** [comment]
Thank you for the info. We create accounts for our clients and use Presentator to interact with them directly.

**Comment by ganigeorgiev** [comment]
@ArjonBu In that case it seems reasonable and I'll add the configuration option(s) for the v2.5.0 release.

**Comment by ArjonBu** [comment]
Thank you. Maybe a "Contact" button or something like that, that replaces the "Send feedback" button at the footer. I would say that this button doesn't make a lot of sense to have it all the time in the footer because it will be rarely used. If someone has a suggestion, he/she will probably open an issue in the github repo. Maybe you can move this to settings or somewhere else.

**Comment by ganigeorgiev** [comment]
@ArjonBu The following new SPA configurations were introduced in v2.5.0:
- `VUE_APP_SHOW_SEND_FEEDBACK` - Boolean option (`0` or `1`) to hide/show the feedback footer link.
- `VUE_APP_FOOTER_LINKS` -  Optional custom footer links in the format `name|url, name2|url2, ...`. Example:
  ```
  VUE_APP_FOOTER_LINKS = Privacy policy|https://example.com/policy, Contacts|https://example.com/contacts
  ```
