### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by vocso** [presentator/presentator#136]
Hello Buddy,

Hope this email finds you well in the times of this pandemic. 
I wanted to thank you for creating such a wonderful project. I am trying to set it up on an AWS instance and always getting stuck. 

The main problems I'm facing are...
1) Confusions around various repositories and setups
2) Paths are not clear. Like where the presentator-api should be and where the starter should be. and then where finally the main repo setup.

I've setup the presentator-api and successfully migrated the db as well.
I'm stuck at setting up starter. It's unable to connect to the database. I believe this has something to do with the location of starter folder in relation to the api.

I have not tried setting main repo yet as I think that wont make sense.

Thank you in advance for your reply. 

Regards,
Deepak

**Comment by ganigeorgiev** [comment]
@vocso Sorry about the confusions.

The [main Presentator repo](https://github.com/presentator/presentator) is a monorepo and contains all Presentator related code (libraries and plugins) in one place. It is used primarily only for easier development and management of the project.

In general, in order to setup Presentator you need to install only 2 packages - [presentor-api](https://github.com/presentator/presentator-api) (backend) and [presentator-spa](https://github.com/presentator/presentator-spa) (frontend). That's all.

The problem with installing them separately is that you'll need to take care for the updates of each package manually. And in addition, [presentator-spa](https://github.com/presentator/presentator-spa) requires Node.js to generate the build/dist files.

To make the installation and updates easier, [presentator-starter](https://github.com/presentator/presentator-starter) was created.
It is a simple composer project configuration that wraps all necessary components to install the application and **it is the recommended way to go for production setup**. It also makes use of the pregenerated SPA build files so Node.js is not required to be installed on the server. Because of the semantic versioning, with the starter package you'll also have clear and full control over the installed version of the platform and its components.

**So for production setup just follow the [presentator-starter instructions](https://github.com/presentator/presentator-starter#installation).**

If you need further help, please comment and I'll reopen the issue.
