### ISSUE TITLE
abuse reporting capabilities

### ISSUE THREAD

**Issue by atari0072** [presentator/presentator#147]
It would be nice to have some kind of abuse reporting capabilities.  I keep getting malicious emails pointing to your site/app/api.   

example:  https://app.presentator.io/#/96jOhDvN/prototypes/19759/screens/118829?mode=preview

It would be nice to have a way to report this and get these apps removed/blocked.

Atari007

**Comment by ganigeorgiev** [comment]
@atari0072 Thank you for submitting the issue. I've just inactivated the spam users. "Report" control will be added in the next release. I'll also consider adding a parameter to disable the ability to set external url to hotspots.

**Comment by ganigeorgiev** [comment]
Just to let you know that a quick "fix" landed in v2.6.1 (I've added a new client side option `VUE_APP_ALLOW_HOTSPOTS_URL`) and for the free service url hotspots are temporary disabled.

This weekend I'll try to find time to add a proper report form/button.

**Comment by atari0072** [comment]
Wow!  I really didnt expect to hear anything back!   You guys are awesome!
 Thank you for letting me know about that.   Keep up the great work!!

**Comment by ganigeorgiev** [comment]
A report form was introduced in [v2.6.2 release](https://github.com/presentator/presentator/releases/tag/v2.6.2). It could be found under the "Preview Info" popover:
![screenshot](https://i.imgur.com/QSLOAAC.png).

_note: published as minor bug fixes release because the new feature most likely will be useful only for the free service (aka. app.presentator.io)_
