### ISSUE TITLE
Update screen bug make me crazy !

### ISSUE THREAD

**Issue by phobiahz** [presentator/presentator#150]
Hi all,

first of all presentator is a great tool ! Unfortunately I encounter a big issue with screen update :

Sometime when I replace a screen, the first time all works fine. When I want to replace the same screen a second time, the screen isn't updated correctly and show me the initial first version of the screen uploaded... 

Is this a bug or am I doing something wrong ?

**Comment by ganigeorgiev** [comment]
@phobiahz Hm, this could be a cache if all of the replacements have the same name.

You probably doesn't encounter the issue on the first replace because the uploaded file name is incremented if already exist (see [FileStorageBehavior.php#L143-L149](https://github.com/presentator/presentator/blob/master/packages/api/behaviors/FileStorageBehavior.php#L143-L149)).
On the second replace, since the new file name doesn't exist on the file system (after the replace the old screen image is deleted) it will be stored under the same name as the first file before the replace but the browser has cached that.

This weekend I'll investigate it further and will consider adding a timestamp instead of a counter (or maybe both) so that all replacements are saved under a different file name.

**Comment by phobiahz** [comment]
@ganigeorgiev 

Thank you for your answer. Yes, the screens have the same filename, when I use a private tab in chrome, the screen is correctly displayed, it is therefore the browser cache that shows me the wrong screen.

**Comment by ganigeorgiev** [comment]
@phobiahz The cache issue should be fixed with the latest v2.6.3 release.
