### ISSUE TITLE
Feature request: option to hide the previous and next arrows in the presentation mode

### ISSUE THREAD

**Issue by Verhoeckx** [presentator/presentator#154]
Hello Gani / Presentator developers,

I have the following feature request:
Is it possible to add an option to hide the previous and next arrows in the presentation mode?

Why?
Well, this way the user is 'forced' to use the hotspots in the images and not distracted by the arrows (well, this last point is a little exaggeration). By forcing the user to use the hotspots it's a little bit more real lifelike.

Regards,

Verhoeckx

**Comment by ganigeorgiev** [comment]
It is possible but, in order to avoid "cluttering" the ui, I'm against adding a config option just to hide the nav arrows (they should be already "half" visible and unobtrusive at least for desktop prototypes).

I'll close the issue for now, but if someone else disagree, please comment and I'll reconsider it.

_p.s. This could be also implemented as part of a bigger "User scenarios (A/B) test" feature that I'm planning, but that will be handled in another issue once I manage to find time to work on it._

**Comment by Verhoeckx** [comment]
Hello Gani,

I understand your reasons! Thanks for 'listing' to the request. 

Thanks for the program and good luck!

**Comment by ganigeorgiev** [comment]
Just for info if someone end up here from googlesearch - this is partially implemented in v2.10.0.

The screen navigation will not be displayed, if the following conditions are met:
1. Is in Preview mode
2. The current active screen has at least one hotspot
3. The preview bar is hidden
