### ISSUE TITLE
Login using Password manager

### ISSUE THREAD

**Issue by der-On** [presentator/presentator#156]
As a user I want to be able to use a password manager to login to presentator.

## Actual Behaviour

- I open the login page of presentator
- I open my password manager
- I tell my password manager to autofill the login form
- Password manager fills in fields
- I click on login button
- Input fields are becoming empty and I get message that Account details are wrong

## Expected Behaviour

- I open the login page of presentator
- I open my password manager
- I tell my password manager to autofill the login form
- Password manager fills in fields
- I click on login button
- I get logged in

## Technical implications

Most SPAs and SPA frameworks do not deal with input fields beeing filled by a non human very well.
They listen for events like keyup to actually fill internal state with some input value. However a password manager will simply set the value of an input field and eventually fire a change or input event on that field. But this depends.

A workaround on most JS driven Login pages is to click into the fields manually and e.g. add a space character and remove it again in each input field, to make the SPA store the new input values.

Instead SPAs therefore should take the input field value in the moment when submitting the form, instead of relying on event handlers to detect changed values. At least in login forms.

**Comment by ganigeorgiev** [comment]
@der-On Although I'm not a fan of browser password managers (especially those that try to insert their own ui in the client's html) but just tested with Bitwarden and Dashlane on Firefox 82 and both seems to work correctly. What password manager are you using?

**Comment by der-On** [comment]
@ganigeorgiev Thank you for testing. I'm using KeePass Tusk as autotype in keepass desktop is not working for me. I will try with another one. You can close the issue now. Sorry

**Comment by ganigeorgiev** [comment]
@der-On Although I could implement a workaround in Presentator, in my opinion this should be fixed in the Tusk extension. There seems to be an open issue describing similar bug - [Tusk#197](https://github.com/subdavis/Tusk/issues/197) (also note that this extension [is no longer maintained](https://github.com/subdavis/Tusk#tusk-is-no-longer-actively-maintained)).

I'll close the issue for now, but if someone stumbled upon this, please comment with the password manager you are using and I'll try to investigate it further.
