### ISSUE TITLE
Bug: animation of fixed element when fading to a screen

### ISSUE THREAD

**Issue by dmartinjs** [presentator/presentator#177]
In preview mode, 
when clicking an hotspot with fading animation, 
if a fixed footer or fixed header are set,
those fixed element are animated strangely.

https://user-images.githubusercontent.com/53537199/110844323-93760000-82a9-11eb-9ac7-104fb518f8e0.mp4

**Comment by ganigeorgiev** [comment]
Should be fixed in v2.9.3. If host Presentator on your own server, just run `composer update` in the project root directory.

_Note: unfortunately some "flickering" may still occur if the transitioned screen is not loaded yet or the screen is with very large resolution and the browser is having difficulties rendering it._

**Comment by dmartinjs** [comment]
It is solved !

yes, just a little flickering since I'm using x2 images, 
but it is good for me now.

Thanks for the quickfix.
