### ISSUE TITLE
Issue with initial migration and postgresql

### ISSUE THREAD

**Issue by CleyFaye** [presentator/presentator#184]
Hi,

When trying Presentator Starter using a PostgreSQL database, migrations fails to apply because the default value provided for boolean columns is either `0` or `1` instead of `false` or `true`.

I have no mean of testing if such simple fix works fine for other database engines, but it did work fine for PostgreSQL.

**Comment by ganigeorgiev** [comment]
Thanks for reporting the issue.

PostgreSQL supports '0' and '1' for boolean columns but as strings (https://www.postgresql.org/docs/current/datatype-boolean.html).

I've totally missed that. I expected the schema builder to abstract and normalize them.
Unfortunately the issue here may not be only with the migrations, because I'm passing 0 and 1 to the app queries too.

I will test it more thoroughly over the weekend and will apply the necessary fixes.

**Comment by ganigeorgiev** [comment]
A fix was released in Presentator v2.13.1. The boolean column operations were normalized and the automation tests were updated to run correctly with both MySQL and PostgreSQL.

If you still experience issues with the PostgreSQL, please let me know and I'll investigate it further.
