### ISSUE TITLE
Error when uploading large images

### ISSUE THREAD

**Issue by Enver-Simsek** [presentator/presentator#193]
Hi Gani, brilliant tool. Thanks for this. Currently I have some problem when I upload larger images. E.g. 3480x14430px, 5,4mb PNG. Then I get an error message and I can't open the project afterwards. Do you know this case? If yes, how can I fix it? Thanks a lot for your help.

**Comment by ganigeorgiev** [comment]
It is most likely failing the thumb generation due to a memory limitation.

Are you using the public free service (app.presentator.io) or self-hosting it on your own?
If the latter, you can try to increase the `memory_limit` in your `php.ini` configuration.

If increasing the `memory_limit` doesn't solve it, you can try to pregenerate the thumb with:
```sh
php /path/to/starter/yii screens/generate-thumbs
```

I'll close the issue for now, but if you are experiencing the issue on the public service feel free to let me know by providing information about your user at `support [at] presentator.io` and I'll try to investigate it.

---

_Side-note: the issue with the memory footprint will be resolved with the upcoming v3 release (_I expect to finalize it in the next couple months_). It will come with major performance boost and significant faster thumbs generation (even with 8k screens based on my local tests)._
