### ISSUE TITLE
Hotspot Templates

### ISSUE THREAD

**Issue by der-On** [presentator/presentator#54]
As a user I would like to reduce the boilerplate of adding the same hotspots in every screen for recuring elements.

## Current situation

- I have a home button on every screen, that brings me to the home page
- I need to create the same hotspot on every screen for that button
- I have a recuring button on half of my screens that brings me to the contact page
- I need to create the same hotsport for every contact button on half of my screens

## Ideal situation

- I have a home button on every screen, that brings me to the home page
- I create a hotspot template "home-button" for the home button and apply it to every screen
- I have a recuring button on half of my screens that brings me to the contact page
- I create another hotspot templatene "contact-button" and apply it to half of my screens

**Comment by ganigeorgiev** [comment]
This was suggested during the beta, but after a discussion with the other contributors I've decided to not implement it since it will unnecessarily results in more complex UI.

As an alternative to the template model, you could duplicate multiple hotsposts to other screens by selecting hotspots with "Shift + Left click" and choose the appropriate screen from the bottom page dropdown panel.
You could also check this blog post for other "hidden features" - https://presentator.io/en/blog/hidden-features

If you still think that the hotspots template is a good idea, please reopen the ticket and I'll be glad for any suggestions about how the interface should look and react, what actions (create/update/copy/delete) should be available, etc.

**Comment by der-On** [comment]
@ganigeorgiev Thank you for the reply. I've already taken a look at the "hidden" features post. However having templates still makes a lot of sence. UI whise we can have a look on how Invision solved that. I will try to come up with some design sketches for this feature.

**Comment by der-On** [comment]
Here ist the prototype: https://app.presentator.io/de/Tu1oPbRG

**Comment by der-On** [comment]
@ganigeorgiev Please reopen the issue as I'm not allowed to do so.

**Comment by ganigeorgiev** [comment]
Implemented in v2 (master).
