### ISSUE TITLE
Overlay screens

### ISSUE THREAD

**Issue by der-On** [presentator/presentator#55]
As a user I want to overlay the current screen with another that contains a transparent background to be able to add things like dialogs, side-navs or other overlaying elements.

## Current situation

- I have a a button toggling a side-navigation, that should lay on top of my screen
- I need to create each screen twice in my graphics application, one with and one without the side-navigation
- I need to link the button toggling the side-navigation in each screen to the corresponding other screen including the side-navigation

## Ideal situation

- I have a a button toggling a side-navigation, that should lay on top of my screen
- I only create a screen in my graphics application with the side-navigation and a transparent background
- I link the button toggling the side-navigation to *overlay* using the side-navigation screen

**Comment by ganigeorgiev** [comment]
Thanks for the suggestion. I'll consider implement it, but since it will require some major frontend changes,  it will be eventually introduced in v2 release.

_Until then, as an alternative most of the designers I've worked with usually export 2 different screens (one with the dialog/panel open, and one with the dialog/panel closed)._

**Comment by der-On** [comment]
Here is the prototype: https://app.presentator.io/en/roO8LmFy?v=0&s=1&m=preview

**Comment by der-On** [comment]
Corresponding WIP PR: https://github.com/ganigeorgiev/presentator/pull/82

**Comment by ganigeorgiev** [comment]
Implemented in v2 (master).
