### ISSUE TITLE
Proposal : Show shared projects from Dashboard

### ISSUE THREAD

**Issue by Laul0** [presentator/presentator#86]
# Current behavior

Currently, it's possible to manage project admins and share project with other people by fill out the email of the targeted people.
The admins can see them projects but not other projects that can be accessible for them.

# Expected behavior

**Use case** : i'm working with developers and my customers who have an account on presentator. This persons are concerned on several project without be systematically admin of them.

The idea is, if this people have an account and a project is shared with them, they can see this projects from them dashboard.

**Comment by ganigeorgiev** [comment]
Because it is possible to share a project by just sending an email with the link outside of the platform and in addition the project link could be restricted to access only the guildeline or a specific prototype,  I've decided to implement a more generic approach by creating an activity panel that shows your recently accessed project links (included in v2.4.0 release). 

The new panel could be accessed by clicking on the sidebar icon below the notifications.

![activity_panel_icon](https://i.imgur.com/ORoaXqX.png)
