### ISSUE TITLE
Import Adobe XD files

### ISSUE THREAD

**Issue by MDXDave** [presentator/presentator#89]
It would be really nice if we can import an Adobe XD project right into presentator. The xd file itself is just an zip file containing assets and a json file for coordinating the relationships between the screens.

**Comment by ucodi** [comment]
I'm just starting to write a Presentator plugin for Adobe XD to export screens directly from adobe XD to a Presentator project, I think it's a better workflow (I'm using this worflow at the moment with zeplin.io).

**Comment by ganigeorgiev** [comment]
@ucodi That's great, but while developing the plugin keep in mind that v2 will be released in the next 3-4 months and the API may undergo slight changes.

**Comment by ucodi** [comment]
I'll just implement login, list and create projects, delete and upload screens for now, so it'll not be hard to move something to v2.

**Comment by rakshith-ravi** [comment]
Hey @spazola! Were you able to make something? I'd be happy to use such a system with presentator

**Comment by dirtydanee** [comment]
Is there any progress on this feature request? 

Would be interested to using Presentation with Adobe XD from day 1, I am even open to submit some PR-s to speed up the development 😅

**Comment by ganigeorgiev** [comment]
I'll try to focus on the import functionality (and eventually creating a plugin) for v2.3.0 release.

**Comment by ganigeorgiev** [comment]
It turned out that direct `.xd` file import was harder than I initially thought, so instead I created only a plugin to export artboard renditions.

Beta release of the plugin (waiting review from the Adobe team) could be found here - https://github.com/presentator/presentator-xd.

If someone wants to test it, just download the latest `presentator_export.xdx` asset from the release page - https://github.com/presentator/presentator-xd/releases and double click to install it (tested only on Windows VM).

_Note: The auto screen replace functionality, based on the artboard title, will be available after Presentator v2.3.0 release (later this week)._

**Comment by ganigeorgiev** [comment]
The screen replace functionality was released in v2.3.0. Once the plugin is reviewed by Adobe, I'll create a post with more details how to work with it.

**Comment by ganigeorgiev** [comment]
Adobe approved the plugin - https://presentator.io/news/adobe-xd-plugin.
You can now install it directly from the adobe plugins store by searching for **Presentator Export**.

**Comment by MDXDave** [comment]
The plugin is working excellent. 
Thanks for your hard work!
