### ISSUE TITLE
Import from Figma?

### ISSUE THREAD

**Issue by elioqoshi** [presentator/presentator#98]
(Don't want to ask for features out of the blue but was wondering if someone is working on it already)

Is someone working on some Figma import to Presentator? I saw someone did an Adobe XD plugin ( https://github.com/spazola/presentator-plugin ) and was wondering about Figma too

**Comment by ganigeorgiev** [comment]
I don't think anyone has started working on this yet, but I recommend to wait until v2 is released (stable version should be released in the next 1-2 months) since the API will have some changes.

**Comment by elioqoshi** [comment]
@ganigeorgiev is this a possibility now?

**Comment by ganigeorgiev** [comment]
@elioqoshi The new API is publicly available (https://presentator.io/docs/introduction), but I haven't started working on the Figma plugin yet.

**Comment by ganigeorgiev** [comment]
Similar to the [Adobe XD issue](https://github.com/presentator/presentator/issues/89), I couldn't find an easy and reliable way to import a Figma file directly in Presentator and I guess a plugin will be required in this case.

I'll try to implement a Figma plugin like the Adobe XD one for the next release (mid January).
In the meantime, if anyone think that the export flow from the XD plugin could be improved, please comment so I could take it in consideration during development.

**Comment by ganigeorgiev** [comment]
Pre-release version of the plugin (waiting review from the Figma team) could be found here - https://github.com/presentator/presentator-figma.

If someone wants to test it, please follow the [manual installation instructions](https://github.com/presentator/presentator-figma#manually).

*Note: The plugin should work with both the free service (aka. https://app.presentator.io) and a self hosted setup, but because Figma plugins run inside a browser environment, CORS policies apply.*

**Comment by ganigeorgiev** [comment]
Figma approved the plugin.

To install it search for "_Presentator Export_" or visit the plugin's page - https://www.figma.com/c/plugin/791989050714284849/Presentator-Export.
